name: Build and Deploy descriptions

on:
  push:
    branches:
      - converter

permissions:
  contents: write

jobs:
  test_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install ğŸ”§
        run: |
          npm ci
          npm i @icemourne/tool-box @icemourne/description-converter

      - name: Build ğŸ› ï¸
        run: npm run build

      - name: Convert ğŸ› ï¸
        run: npm run convert

      - name: Generate data ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: database # Folder you wish to deploy
          branch: live # Branch you wish to deploy to
          clean: true
          clean-exclude: README.md
