name: Build and Deploy descriptions

on:
  push:
    branches:
    - converter

permissions:
  contents: write

jobs:
  test_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i
      - run: npm run build
      - run: npm run convert

      - name: Generate data ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: database # Folder you wish to deploy
          branch: test
          # target-folder: descriptions
